version: 1
release_name: external-secrets
namespace_template: "lab-${env}"
environments:
  ci:
    namespace: external-secrets
    values:
      - values.yaml
      - values-ci.yaml
triggers:
  "Chart.yaml":     [ci]
  "values.yaml":    [ci]
  "values-ci.yaml": [ci]
  "templates/**":   [ci]
