---
tempo:
  fullnameOverride: tempo
  replicas: 1

  tempo:
    memBallastSizeMbs: 64
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    retention: 24h
    metricsGenerator:
      enabled: true
      remoteWriteUrl: http://mimir-distributed-gateway.observability.svc/api/v1/push
    overrides:
      defaults:
        metrics_generator:
          processors:
            - service-graphs
            - span-metrics
            - local-blocks

  persistence:
    enabled: false

  serviceMonitor:
    enabled: false

  tempoQuery:
    enabled: false

  nodeSelector: {}
  tolerations: []
