---
apiVersion: v2
name: arc-runner-set
description: GitHub Actions Runner Controller runner scale set dependency chart
type: application
version: 0.1.0
appVersion: "0.14.2"
dependencies:
  - name: gha-runner-scale-set
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
