apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmosdb-emulator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmosdb-emulator.labels" . | nindent 4 }}
type: Opaque
stringData:
  account-key: {{ .Values.emulator.accountKey | quote }}
  internal-endpoint: {{ include "cosmosdb-emulator.internalEndpoint" . | quote }}
  internal-connection-string: {{ printf "AccountEndpoint=%s;AccountKey=%s;" (include "cosmosdb-emulator.internalEndpoint" .) .Values.emulator.accountKey | quote }}
  external-endpoint: {{ include "cosmosdb-emulator.externalEndpoint" . | quote }}
  external-connection-string: {{ printf "AccountEndpoint=%s;AccountKey=%s;" (include "cosmosdb-emulator.externalEndpoint" .) .Values.emulator.accountKey | quote }}
