---
apiVersion: v2
name: pyrra
description: pyrra vendor/deployment chart
type: application
version: 0.1.0
appVersion: "v0.8.1"
dependencies:
  - name: pyrra
    version: 1.8.0
    repository: https://pyrra-dev.github.io/helm-charts
