---
apiVersion: v2
name: kiali-operator
description: kiali operator vendor/deployment chart
type: application
version: 0.1.0
appVersion: "v2.28.0"
dependencies:
  - name: kiali-operator
    version: 2.28.0
    repository: https://kiali.org/helm-charts
