---
apiVersion: v2
name: strimzi-kafka-operator
description: Strimzi Kafka Operator vendor/deployment chart
type: application
version: 0.1.0
appVersion: "1.0.1"
dependencies:
  - name: strimzi-kafka-operator
    version: 1.0.1
    repository: https://strimzi.io/charts/
