---
apiVersion: v2
name: flink-operator
description: Apache Flink Kubernetes Operator vendor/deployment chart
type: application
version: 0.1.0
appVersion: "1.15.0"
dependencies:
  - name: flink-kubernetes-operator
    version: 1.15.0
    repository: https://downloads.apache.org/flink/flink-kubernetes-operator-1.15.0/
