apiVersion: v2
name: external-dns
description: ExternalDNS with the OpenStack Designate webhook
type: application
version: 0.1.1
appVersion: "0.21.0"
dependencies:
  - name: external-dns
    version: 1.21.1
    repository: https://kubernetes-sigs.github.io/external-dns/
