---
apiVersion: v2
name: inspektor-gadget
description: inspektor-gadget vendor/deployment chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: gadget
    version: 0.53.1
    repository: https://inspektor-gadget.github.io/charts

