{{- if .Values.serviceMonitors.cilium.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-operator
  namespace: {{ .Values.serviceMonitors.cilium.namespace }}
  labels:
    app.kubernetes.io/part-of: cilium
    app.kubernetes.io/name: cilium-operator
    {{- with .Values.serviceMonitors.cilium.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitors.cilium.namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitors.cilium.interval | quote }}
      honorLabels: true
      path: /metrics
  targetLabels:
    - io.cilium/app
{{- end }}
