---
istio:
  enabled: false

thanos:
  global:
    objstore:
      createSecret: true
      config: |
        type: S3
        config:
          bucket: thanos-metrics
          endpoint: rustfs-svc:9000
          access_key: ci-thanos
          secret_key: ci-thanos-secret-not-for-production
          insecure: true

  rustfs:
    enabled: false

  receive:
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  compactor:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  storegateway:
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  query:
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi

  queryFrontend:
    enabled: false
