version: 1
release_name: chaos-mesh
namespace_template: "lab-${env}"
environments:
  ci:
    values:
      - values.yaml
      - values-ci.yaml
triggers:
  "values.yaml":    [ci]
  "values-ci.yaml": [ci]
