apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamodb-local.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynamodb-local.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.dynamodb.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.dynamodb.secretAccessKey | quote }}
  aws-default-region: {{ .Values.dynamodb.region | quote }}
  internal-endpoint-url: {{ include "dynamodb-local.internalEndpoint" . | quote }}
  external-endpoint-url: {{ include "dynamodb-local.externalEndpoint" . | quote }}
