apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamodb-local.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynamodb-local.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dynamodb-local.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-dynamodb
      port: {{ .Values.dynamodb.port }}
      targetPort: dynamodb
      protocol: TCP
